### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by mikkohyy** [kluopaja/ajanvarausjarjestelma#1]
Käyttökokemus tämänhetkisen version perusteella (12.8. kello 20:08)

- Uuden käyttäjän rekisteröinnissä käyttäjätunnuksen sallittuja merkkejä kuvaavan ([a-zA-Z0-9]+) merkitys ei välttämättä avaudu kunnolla ei-koodareille ja voisi aiheuttaa hämmennystä "oikeassa maailmassa" käyttäjälle
- Käyttäjätunnuksen luomisessa olisi mielekästä olla myös kenttä "salasana uudestaan" varmistamassa ettei uusi käyttäjä typota salasanaansa
- Uuden kyselyn luomisen kohdalla olisi mielekästä, jos sovellus kertoisi jo Lisää kysely -nappia painaessa, jos viimeinen päivä on asetettu ennen ensimmäistä mahdollista päivää (samaan tapaan kuin virheellisestä kellonajasta ilmoitetaan ilman, että siirrytään seuraavaan näkymään)
- Kyselyn päättymisajan valinnassa minuuttien väliset välit voisivat olla viiden minuutin välein
- Voisi olla myös kätevää, jos kutsut voisi linkin jakamisen sijaan tehdä suoraan toisille käyttäjille (eli esimerkiksi tiina voisi hakea listan käyttäjistä, joille voisi lähettää kutsun suoraan)

Sovellus vaikuttaa toimivalta kokonaisuudelta. Se osasi vastata käyttäjälle järkevästi, vaikka käyttäjä teki asioita, joita käyttäjän ei olisi pitänyt tehdä (esimerkiksi asetti aloitus- ja päättymispäivämäärät väärin ja syötti uuden tunnuksen luomisen yhteydessä vääriä merkkejä).

Koodi

- Funktiot ja muuttujat on nimetty mielestäni kuvaavasti ja hyvin
- Tietokannan taulut ovat mielestäni nimetty hyvin ja tietokannan rakenne on mielestäni järkevä
- Osa funktioista on melko pitkiä. Esimerkiksi utils.py -moduulissa riviltä 100 alkava process_new_poll -funktio olisi mahdollista pilkkoa pienempiin funktioihin tekemällä esimerkiksi riveillä 111-123 olevista if-lauseista oman funktionsa
- Utils.py:n voisi pilkkoa pienempiin moduuleihin. Moduulissa itsessään on mielestäni jo oikein hyvin tehty jaottelu sen mukaan mihin kukin funktio liittyy eli moduulin voisi jakaa esimerkiksi moduuleihin user_session_utils, poll_utils, invitation_utils ja resource_utils
- Joissain kohdissa funktiot on eroteltu yhden rivinvaihdon sijaan kahdella tai kolmella rivinvaihdolla
- Koodi on selkeää ja helppolukuista henkilölle, joka tulee projektin ulkopuolelta ja näkee koodin ensimmäistä kertaa

Mielestäni sovellus on oikein hyvässä vaiheessa jo tässä vaiheessa kurssia.

**Comment by kluopaja** [comment]
Kiitos hyödyllisistä kommenteista!
