### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by HyTom** [kluopaja/ajanvarausjarjestelma#2]
Hei!
Tässä vertaisarviointini projektistasi.

Käyttäjän ja kyselyn luominen oli sujuvaa.
Olisi ehkä voinut olla mukavaa asettaa kyselyn päättymisajaksi esim. tyypillinen 23:59.
Kyselyä tutkiessa uutena käyttäjänä olisi kiva jos "Optimoi ajanvaraukset" napin vieressä olisi teksti joka kuvaisi mitä se tekee.
Voisi myös olla mukavaa jos luodut resurssikutsulinkit antaisivat koko URL:in, niin se olisi helpompi jakaa.

Luin läpi koodia, se oli hyvin kommentoitua ja mukava lukea.
Pääkansiossasi on jo aika paljon tavaraa, ehkä niitä voisi järjestää kansioihin?

Onnea projektiin!

**Comment by kluopaja** [comment]
Kiitos hyvistä kommenteista!
